const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),test=require('node:test'),C=require('../assets/exams/core.js'),lib=require('../assets/vendor/pdf-lib/pdf-lib.min.js');
const root=path.resolve(__dirname,'..'),all=JSON.parse(fs.readFileSync(path.join(root,'exams/data/exam-index.json'))),rows=all.filter(q=>q.qualification==='GCSE Maths');
test('GCSE Higher bank: complete papers, metadata, unique IDs and readable PDF paths',async()=>{
 assert.equal(rows.length,997);assert.equal(new Set(all.map(q=>q.id)).size,all.length);
 const papers=new Map();for(const q of rows){assert.equal(q.tier,'Higher');assert.equal(q.examBoard,'Pearson Edexcel');assert.equal(q.paper,'P'+q.paperNumber);assert.equal(q.paperCode,'1MA1/'+q.paperNumber+'H');assert(['june','november'].includes(C.examSeries(q)));assert(q.subtopic);assert(['Number','Algebra','Ratio, Proportion and Rates of Change','Geometry and Measures','Probability','Statistics'].includes(q.topic));if(!papers.has(q.sourceFile))papers.set(q.sourceFile,[]);papers.get(q.sourceFile).push(q);
 assert(C.safePath(q.questionFile,'exams/questions/'));assert(fs.existsSync(path.join(root,q.sourceFile)));const pdf=await lib.PDFDocument.load(fs.readFileSync(path.join(root,q.questionFile)));assert(pdf.getPageCount()>0);for(const p of pdf.getPages()){assert(p.getWidth()>0);assert(p.getHeight()>0);}}
 assert.equal(papers.size,45);for(const qs of papers.values()){assert.equal(qs.reduce((n,q)=>n+q.marks,0),80);assert.deepEqual(qs.map(q=>+q.question).sort((a,b)=>a-b),Array.from({length:qs.length},(_,i)=>i+1));}
});
test('real GCSE records combine paper, series, year and topic filters',()=>{for(const paper of ['P1','P2','P3'])for(const series of ['June','November'])for(const examYear of [2017,2022,2024]){const f={qualification:'GCSE Maths',tier:'Higher',paper,series,examYear};const result=C.filter(all,f);assert(result.length>0);assert(result.every(q=>q.paper===paper&&C.examSeries(q)===series.toLowerCase()&&q.examYear===examYear));for(const topic of C.unique(result.flatMap(C.topics))){const filtered=C.filter(all,{...f,topic});assert(filtered.length>0);assert(filtered.every(q=>C.topics(q).includes(topic)));}}assert.equal(C.filter(all,{qualification:'GCSE Maths',tier:'Foundation'}).length,0);});
