const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),lib=require('../assets/vendor/pdf-lib/pdf-lib.min.js');
const root=path.resolve(__dirname,'..'),all=require('../exams/data/exam-index.json'),samples=[14,1,9,10,13,18,21].map(n=>all.find(q=>q.id==='edexcel-1ma1-1h-2024-june-q'+n));
(async()=>{const out=process.env.ANSWERS_EXPORT_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'pyexams-answers-')),browser=await chromium.launch({headless:true,channel:'chrome'});fs.mkdirSync(out,{recursive:true});
try{const page=await browser.newPage({viewport:{width:1024,height:900},hasTouch:true}),errors=[],requested=[];let failAnswer=false,downloads=0;
page.on('pageerror',e=>errors.push(e.message));page.on('download',()=>downloads++);
await page.route('**/*',r=>{const relative=new URL(r.request().url()).pathname.slice(1),file=path.resolve(root,relative);if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return r.fulfill({status:404});if(relative.endsWith('.pdf'))requested.push(relative);if(failAnswer&&relative===samples[2].answerFile)return r.fulfill({status:404});return r.fulfill({body:fs.readFileSync(file),contentType:({'.js':'application/javascript','.json':'application/json','.css':'text/css','.pdf':'application/pdf','.png':'image/png'})[path.extname(file)]||'text/html'});});
await page.goto('http://answers.test/pyexams.html');await page.selectOption('#qualification','GCSE Maths');await page.selectOption('#tier','Higher');
for(const q of samples)await page.locator('.question-row').filter({has:page.locator(`a[href="${q.questionFile}"]`)}).locator('input').check();
for(const mode of ['off','compact','working']){
 await page.locator('#createPractice').click();assert.equal(await page.locator('#includeAnswers').isChecked(),false);if(mode!=='off')await page.locator('#includeAnswers').tap();if(mode==='working')await page.locator('#includeWorkingSpace').check();await page.locator('#paperTitle').fill('Algebra Practice');
 for(const width of [1440,1024,390]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 requested.length=0;const pending=page.waitForEvent('download');await page.locator('#buildPDF').click();const practice=await pending;assert.equal(practice.suggestedFilename(),'PY-Maths-Algebra-Practice.pdf');await practice.saveAs(path.join(out,mode+'-practice.pdf'));
 const expected=samples.map(q=>mode==='working'?q.workingQuestionFile:q.questionFile);
 if(mode!=='off'){
  expected.push(...samples.map(q=>q.answerFile));const pendingAnswer=page.waitForEvent('download');await page.getByRole('link',{name:'Download answers / mark scheme',exact:true}).click();const answer=await pendingAnswer;assert.equal(answer.suggestedFilename(),'PY-Maths-Algebra-Practice-Answers.pdf');const file=path.join(out,mode+'-answers.pdf');await answer.saveAs(file);const doc=await lib.PDFDocument.load(fs.readFileSync(file));assert.equal(doc.getPageCount(),3);for(const p of doc.getPages())assert.deepEqual(p.getSize(),{width:595.28,height:841.89});
 }else assert.equal(await page.getByRole('link',{name:'Download answers / mark scheme',exact:true}).count(),0);
 assert.deepEqual(requested,expected);
}
// Failed extraction fetch never publishes an incomplete pair of booklets.
await page.locator('#createPractice').click();await page.locator('#includeAnswers').check();failAnswer=true;const before=downloads;await page.locator('#buildPDF').click();await page.getByText(/Question 9: PDF request returned HTTP 404/).waitFor();assert.equal(downloads,before);assert.equal(await page.locator('#downloadResult a').count(),0);assert.equal(await page.locator('#selectedList li').count(),7);assert(await page.locator('#includeAnswers').isEnabled());failAnswer=false;await page.locator('#cancelExport').click();
// A course without official answer coverage is reported before any source PDF request.
const missing=all.find(q=>q.qualification==='A-Level Further Maths'&&!q.answerFile);await page.selectOption('#qualification',missing.qualification);await page.selectOption('#yearGroup',missing.yearGroup);await page.selectOption('#component',missing.component);await page.selectOption('#topic',missing.topic);await page.locator('.question-row').filter({has:page.locator(`a[href="${missing.questionFile}"]`)}).locator('input').check();await page.locator('#createPractice').click();await page.locator('#includeAnswers').check();requested.length=0;await page.locator('#buildPDF').click();await page.getByText(/Missing official mark scheme for:/).waitFor();const message=await page.locator('#exportStatus').textContent();assert(message.includes('Question '+missing.question));assert(message.includes(String(missing.examYear)));assert.deepEqual(requested,[]);assert.equal(await page.locator('#selectedList li').count(),8);assert.equal(downloads,before);assert.deepEqual(errors,[]);
console.log('PASS answers OFF/ON, both working modes, ordered real PDF downloads, exact A4, responsive touch controls, failed fetch and missing-answer preflight. '+out);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
