const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const lib=require('../assets/vendor/pdf-lib/pdf-lib.min.js');
const root=path.resolve(__dirname,'..'),all=JSON.parse(fs.readFileSync(path.join(root,'exams/data/exam-index.json')));
const samples=['1h-2024-june-q10','1h-2017-june-q21','1h-2024-june-q11','1h-2024-june-q3','2h-2018-november-q13','3h-2022-november-q26'].map(id=>all.find(q=>q.id==='edexcel-1ma1-'+id));
(async()=>{const out=process.env.WORKING_EXPORT_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'pyexams-working-'));fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'});
try{const page=await browser.newPage({viewport:{width:1024,height:900},hasTouch:true}),errors=[],requested=[];let failWorking=false;
page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url()),relative=u.pathname.slice(1),f=path.resolve(root,relative);if(!f.startsWith(root+path.sep)||!fs.existsSync(f))return r.fulfill({status:404});if(relative.endsWith('.pdf'))requested.push(relative);if(failWorking&&relative.includes('/working/'))return r.fulfill({status:404});return r.fulfill({body:fs.readFileSync(f),contentType:({'.js':'application/javascript','.json':'application/json','.css':'text/css','.pdf':'application/pdf','.png':'image/png'})[path.extname(f)]||'text/html'});});
await page.goto('http://working.test/pyexams.html');await page.selectOption('#qualification','GCSE Maths');await page.selectOption('#tier','Higher');
for(const q of samples)await page.locator('.question-row').filter({has:page.locator(`a[href="${q.questionFile}"]`)}).locator('input').check();
for(const working of [false,true]){await page.locator('#createPractice').click();assert.equal(await page.locator('#includeWorkingSpace').isChecked(),false);assert.equal(await page.locator('#includeWorkingSpace').isEnabled(),true);
if(working)await page.locator('#includeWorkingSpace').tap();await page.locator('#paperTitle').fill('Working Space Comparison');
for(const width of [1440,1024,390]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(working)await page.screenshot({path:path.join(out,'dialog-'+width+'.png')});}
requested.length=0;const download=page.waitForEvent('download');await page.locator('#buildPDF').click();const file=path.join(out,working?'original-working-space.pdf':'compact.pdf');await(await download).saveAs(file);
assert.deepEqual(requested,samples.map(q=>working?q.workingQuestionFile:q.questionFile));const pdf=await lib.PDFDocument.load(fs.readFileSync(file));for(const p of pdf.getPages())assert.deepEqual(p.getSize(),{width:595.28,height:841.89});console.log((working?'Working':'Compact')+' sample: '+pdf.getPageCount()+' A4 pages.');}
// Missing working PDFs must show a clear error without changing the selection or silently falling back.
await page.locator('#createPractice').click();await page.locator('#includeWorkingSpace').check();failWorking=true;await page.locator('#buildPDF').click();await page.getByText(/PDF request returned HTTP 404/).waitFor();assert.equal(await page.locator('#selectedList li').count(),samples.length);assert(await page.locator('#includeWorkingSpace').isEnabled());failWorking=false;await page.locator('#cancelExport').click();
// Other courses have no fabricated working variant. Mixed selections explain the fallback.
await page.selectOption('#qualification','A-Level Further Maths');await page.selectOption('#yearGroup','Year 1');await page.selectOption('#component','Pure');await page.selectOption('#topic','Matrices');await page.locator('.question-row input').first().check();await page.locator('#createPractice').click();assert.match(await page.locator('#workingSpaceHelp').textContent(),/6 of 7/);await page.locator('#cancelExport').click();
await page.locator('#clearSelection').click();await page.locator('.question-row input').first().check();await page.locator('#createPractice').click();assert(await page.locator('#includeWorkingSpace').isDisabled());assert.equal(await page.locator('#includeWorkingSpace').isChecked(),false);assert.deepEqual(errors,[]);
console.log('PASS real PDF selection in both modes, default reset, desktop/iPad/mobile checkbox, multi-page export, failure retention, mixed-course disclosure and unavailable-course handling. '+out);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
