/* Optional real-browser acceptance test. Run with PLAYWRIGHT_MODULE set to your Playwright installation. */
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),lib=require('../assets/vendor/pdf-lib/pdf-lib.min.js');
(async()=>{
 const root=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(os.tmpdir(),'pyexams-practice-'));
 async function pdf(number,pages=1,rotation=0){const d=await lib.PDFDocument.create();for(let i=0;i<pages;i++){const p=d.addPage([595,842]);p.drawRectangle({x:4,y:4,width:587,height:834,borderWidth:1,borderColor:lib.rgb(0,.2,.6)});p.drawText('SYNTHETIC TEST QUESTION '+number+' - PAGE '+(i+1),{x:25,y:790,size:16});p.drawText('(a) Solve x + 2 = 5. [3]',{x:25,y:740,size:16});p.drawLine({start:{x:30,y:650},end:{x:550,y:400},thickness:2});p.drawText('Last subpart and marks [6]',{x:25,y:25,size:16});p.setRotation(lib.degrees(rotation));}return Buffer.from(await d.save());}
 const entries=[['q1','Complex Numbers',2019,7,12],['q2','Complex Numbers',2024,8,9],['q3','Matrices',2022,5,5]].map(([id,topic,examYear,question,marks])=>({id,topic,examYear,question:String(question),marks,examSeries:'June',qualification:'A-Level Further Maths',yearGroup:'Year 2',component:'Pure',tier:'',examBoard:'OCR',paperCode:'Y410/01',subtopics:topic==='Matrices'?['Inverse']:['Argand Diagrams'],questionFile:'exams/questions/'+id+'.pdf',sourceFile:'exams/source/test.pdf'}));
 const pdfs={'/exams/questions/q1.pdf':await pdf('7'),'/exams/questions/q2.pdf':await pdf('8',2),'/exams/questions/q3.pdf':await pdf('5',1,90)};
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});let fail=false;
 try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='py-maths.test')return route.abort();if(u.pathname==='/exams/data/exam-index.json')return route.fulfill({json:entries});if(pdfs[u.pathname])return route.fulfill({status:fail&&u.pathname.endsWith('q2.pdf')?404:200,contentType:'application/pdf',body:pdfs[u.pathname]});const file=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return route.fulfill({status:404,body:'Missing'});const ext=path.extname(file);return route.fulfill({body:fs.readFileSync(file),contentType:ext==='.js'?'application/javascript':ext==='.css'?'text/css':ext==='.png'?'image/png':'text/html'});});
 await page.goto('http://py-maths.test/pyexams.html');await page.selectOption('#qualification','A-Level Further Maths');await page.selectOption('#yearGroup','Year 2');await page.selectOption('#component','Pure');await page.selectOption('#topic','Complex Numbers');
 await page.getByRole('checkbox',{name:/2019 question 7/}).check();assert.match(await page.locator('#basketSummary').textContent(),/1 selected · 12 marks/);
 await page.locator('#createPractice').click();assert.equal(await page.locator('#paperTitle').inputValue(),'Complex Numbers Practice');await page.locator('#cancelExport').click();
 await page.selectOption('#examYear','2024');assert.match(await page.locator('#basketSummary').textContent(),/1 selected/);await page.getByRole('checkbox',{name:/2024 question 8/}).check();await page.selectOption('#examYear','');await page.selectOption('#topic','Matrices');await page.getByRole('checkbox',{name:/2022 question 5/}).check();assert.match(await page.locator('#basketSummary').textContent(),/3 selected · 26 marks/);
 const move=()=>page.getByRole('button',{name:/Move up question 5/}).click();await move();await move();assert.match(await page.locator('#selectedList li').first().textContent(),/Matrices/);
 await page.getByRole('button',{name:/Remove question 7/}).click();assert.match(await page.locator('#basketSummary').textContent(),/2 selected · 14 marks/);await page.selectOption('#topic','Complex Numbers');await page.getByRole('checkbox',{name:/2019 question 7/}).check();
 await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
 await page.locator('#createPractice').click();await page.locator('#paperTitle').fill('Mixed Topics Practice');const downloaded=page.waitForEvent('download');await page.locator('#buildPDF').click();const download=await downloaded;await download.saveAs(path.join(output,'practice.pdf'));assert.equal(download.suggestedFilename(),'PY-Maths-Mixed-Topics-Practice.pdf');assert.equal((await lib.PDFDocument.load(fs.readFileSync(path.join(output,'practice.pdf')))).getPageCount(),4);
 fail=true;await page.locator('#createPractice').click();await page.locator('#buildPDF').click();await page.waitForFunction(()=>document.getElementById('exportStatus').textContent.includes('HTTP 404'));assert.match(await page.locator('#exportStatus').textContent(),/June 2024 · Question 8/);assert.equal(await page.locator('#selectedList li').count(),3);assert.equal(await page.locator('#downloadResult a').count(),0);await page.locator('#cancelExport').click();
 await page.setViewportSize({width:820,height:1180});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(output,'ipad.png'),fullPage:true});await page.locator('#createPractice').click();assert.ok(await page.locator('#buildPDF').isVisible());await page.locator('#cancelExport').click();await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#clearAll').click();assert.equal(await page.locator('#selectedList li').count(),0);assert.equal(await page.locator('#createPractice').isDisabled(),true);assert.deepEqual(errors,[]);console.log('PASS: desktop/iPad/mobile selection, cross-filter persistence, order, remove, download and failure retention. Artifacts: '+output);
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
