const test=require('node:test'),assert=require('node:assert/strict');
const P=require('../assets/exams/practice.js'),lib=require('../assets/vendor/pdf-lib/pdf-lib.min.js');
const q=(id,topic='Complex Numbers',year=2024)=>({id,topic,examBoard:'OCR',qualification:'A-Level Further Maths',paperCode:'Y410/01',examYear:year,examSeries:'June',question:id,marks:9});
test('basket selects uniquely, persists across topics, reorders, removes and totals marks',()=>{const b=new P.Basket(),a=q('1'),c=q('2','Matrices',2019);b.add(a);b.add(a);b.add(c);assert.equal(b.items.length,2);assert.equal(b.marks,18);b.move('2',-1);assert.deepEqual(b.items.map(e=>e.id),['2','1']);b.move('2',-1);assert.equal(b.items[0].id,'2');b.remove('1');assert.equal(b.marks,9);b.clear();assert.equal(b.items.length,0);});
test('source label uses actual board, series/year and marks; missing series is not invented',()=>{assert.deepEqual(P.sourceLines(q('8')),['OCR · A-Level Further Maths · Y410/01','June 2024 · Question 8 · 9 marks']);assert.equal(P.sourceLines({...q('3'),examBoard:'AQA'})[0].startsWith('AQA'),true);assert.equal(P.series({...q('3'),examSeries:''}),'2024');assert.equal(P.series({...q('3'),examSeries:'June 2024'}),'June 2024');assert.equal(P.filename('../Complex Numbers: Practice?'),'PY-Maths-Complex-Numbers-Practice.pdf');assert.equal(P.filename('///'),'PY-Maths-Practice.pdf');});
async function fixture(rotation=0){const doc=await lib.PDFDocument.create();for(let i=0;i<2;i++){const page=doc.addPage([600,800]);page.drawText('Original mathematics x + y = 3',{x:20,y:760});page.drawRectangle({x:5,y:5,width:590,height:790,borderWidth:1});page.setRotation(lib.degrees(rotation));}return doc.save();}
test('every question page has accurate mandatory headers and source remains vector content',async()=>{const texts=[],forms=[],realCreate=lib.PDFDocument.create.bind(lib.PDFDocument);const adapter={...lib,PDFDocument:{load:lib.PDFDocument.load.bind(lib.PDFDocument),create:async()=>{const d=await realCreate(),add=d.addPage.bind(d);d.addPage=(...args)=>{const p=add(...args),t=p.drawText.bind(p),draw=p.drawPage.bind(p);p.drawText=(text,opts)=>{texts.push(text);return t(text,opts);};p.drawPage=(embedded,opts)=>{forms.push({opts,size:p.getSize()});return draw(embedded,opts);};return p;};return d;}}};const bytes=await fixture(),data=await P.build([q('8'),{...q('5','Matrices',2019),examBoard:'AQA',marks:12}],{title:'Mixed Topics Practice',lib:adapter,load:async()=>bytes});const out=await lib.PDFDocument.load(data);assert.equal(out.getPageCount(),4);assert.equal(texts.filter(t=>t.includes('PY Maths')).length,1);assert.equal(texts.filter(t=>t.includes('June 2024 · Question 8 · 9 marks')).length,2);assert.equal(texts.filter(t=>t.includes('June 2019 · Question 5 · 12 marks')).length,2);assert.equal(texts.filter(t=>t.startsWith('AQA')).length,2);assert.equal(forms.length,4);for(const {opts,size} of forms){assert.ok(opts.x>=0&&opts.y>=0);assert.ok(opts.x+opts.width<=size.width);assert.ok(opts.y+opts.height<size.height-40);assert.ok(Math.abs(opts.width/opts.height-.75)<1e-9);}assert.ok(out.context.enumerateIndirectObjects().some(([,o])=>String(o).includes('/Subtype /Form')));});
test('all right-angle rotations export safely and failed questions identify source without output',async()=>{for(const rotation of [0,90,180,270]){const data=await fixture(rotation);const out=await lib.PDFDocument.load(await P.build([q('8')],{title:'Practice',lib,load:async()=>data}));assert.equal(out.getPageCount(),2);}await assert.rejects(()=>P.build([q('8'),q('5','Matrices',2019)],{lib,load:async e=>{if(e.question==='5')throw Error('HTTP 404');return fixture();}}),/OCR Y410\/01 · June 2019 · Question 5: HTTP 404/);await assert.rejects(()=>P.build([q('8')],{lib,load:async()=>new Uint8Array([1,2,3])}),/Question 8/);});

async function sized(width,height){const d=await lib.PDFDocument.create();const p=d.addPage([width,height]);p.drawRectangle({x:1,y:1,width:width-2,height:height-2,borderWidth:1});return d.save();}
test('short questions flow on one exact A4 sheet; mixed sizes move intact without shrinking to fill space',async()=>{
 const sources={a:await sized(500,100),b:await sized(500,300),c:await sized(500,300)};
 const placements=[];const adapter={...lib,PDFDocument:{load:lib.PDFDocument.load.bind(lib.PDFDocument),create:async()=>{const d=await lib.PDFDocument.create(),add=d.addPage.bind(d);d.addPage=(...args)=>{const p=add(...args),draw=p.drawPage.bind(p);p.drawPage=(e,o)=>{placements.push({page:d.getPageCount(),...o});return draw(e,o);};return p;};return d;}}};
 const bytes=await P.build([q('a'),q('b'),q('c')],{lib:adapter,load:e=>sources[e.id]});const d=await lib.PDFDocument.load(bytes);
 assert.equal(d.getPageCount(),2);for(const p of d.getPages())assert.deepEqual(p.getSize(),{width:595.28,height:841.89});
 assert.deepEqual(placements.map(p=>p.page),[1,1,2]);assert.deepEqual(placements.map(p=>p.height),[100,300,300]);assert.ok(placements[1].y+300<placements[0].y-28);
 const short=await lib.PDFDocument.load(await P.build([q('a'),q('a'),q('a'),q('a')],{lib,load:()=>sources.a}));assert.equal(short.getPageCount(),1);
});
test('oversized source pages fit A4 without dropping content',async()=>{
 const data=await sized(700,1500);const out=await lib.PDFDocument.load(await P.build([q('1')],{lib,load:()=>data}));assert.deepEqual(out.getPage(0).getSize(),{width:595.28,height:841.89});
});
